name: Continuous Integration and Continuous Delivery (CI/CD)

on:
  push:
    branches:
      - main
    paths:
      - "scacchi/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/CI.yml

  continuous-delivery:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    needs: continuous-integration

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Define image tag
        id: define_img_tag
        run: |
          TEAM_NAME="$(echo $GITHUB_REPOSITORY | cut -d'/' -f 2 | cut -d'-' -f 2)"
          IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/scacchi-${TEAM_NAME}
          IMAGE_TAG=$(echo "$IMAGE_TAG" | tr "[:upper:]" "[:lower:]")
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.define_img_tag.outputs.image_tag }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
